version: '3.8'
services:
  dbaudit.web:
    image: dbaudit.web
    build:
      context: .
      dockerfile: ../DBAudit.Web/Dockerfile
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongP@ssw0rd"
      MSSQL_PID: "Developer"
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data:
